In [4]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer


In [46]:
from nltk.corpus import movie_reviews

pos_rev = movie_reviews.fileids('pos')
neg_rev = movie_reviews.fileids('neg')


In [47]:
import nltk

rev = nltk.corpus.movie_reviews.words('pos/cv000_29590.txt')
print(len(rev))
print(rev)

862
['films', 'adapted', 'from', 'comic', 'books', 'have', ...]


### Cleaning and combining all Positive and Negative reviews

In [48]:
rev_list = []
for rev in neg_rev:
    rev_text_neg = rev = nltk.corpus.movie_reviews.words(rev)
    review_one_string = " ".join(rev_text_neg)
    review_one_string = review_one_string.replace(' ,',',')
    review_one_string = review_one_string.replace(' .','.')
    review_one_string = review_one_string.replace("\'" ,"'")
    review_one_string = review_one_string.replace(" \'" ,"'")
    rev_list.append(review_one_string)

len(rev_list)

1000

In [10]:
for rev in pos_rev:
    rev_text_pos = rev = nltk.corpus.movie_reviews.words(rev)
    review_one_string = " ".join(rev_text_neg)
    review_one_string = review_one_string.replace(' ,',',')
    review_one_string = review_one_string.replace(' .','.')
    review_one_string = review_one_string.replace("\'" ,"'")
    review_one_string = review_one_string.replace(" \'" ,"'")
    rev_list.append(review_one_string)
len(rev_list)

2000

In [11]:
# print(rev_list[1231])

In [12]:
neg_targets = np.zeros((1000,),dtype = np.int)
pos_targets = np.ones((1000,),dtype = np.int)

target_list = []
for neg_tar in neg_targets:
    target_list.append(neg_tar)
for pos_tar in pos_targets:
    target_list.append(pos_tar)

In [13]:
y = pd.Series(target_list)
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int64

# ------------------- Create Features -------------------
We will use the Count Vectorizer and Bag of Words

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(lowercase = True,stop_words="english",min_df=2)

X_count_vect = count_vect.fit_transform(rev_list)

print(X_count_vect.shape)
print(X_count_vect[10,:])
# print(X_count_vect.shape)

(1000, 16209)
  (0, 3908)	1
  (0, 11600)	1
  (0, 13930)	1
  (0, 11407)	1
  (0, 5140)	1
  (0, 11855)	1
  (0, 13407)	1
  (0, 1603)	1
  (0, 12865)	1
  (0, 3262)	1
  (0, 11738)	1
  (0, 10581)	1
  (0, 16096)	1
  (0, 1976)	1
  (0, 16069)	1
  (0, 2566)	1
  (0, 15050)	1
  (0, 2996)	1
  (0, 14120)	1
  (0, 14507)	1
  (0, 12610)	1
  (0, 559)	1
  (0, 10871)	1
  (0, 8239)	1
  (0, 10985)	1
  :	:
  (0, 12345)	1
  (0, 6075)	2
  (0, 9479)	1
  (0, 1529)	2
  (0, 15754)	1
  (0, 6464)	1
  (0, 344)	3
  (0, 15681)	2
  (0, 1484)	9
  (0, 4246)	1
  (0, 5430)	1
  (0, 14566)	1
  (0, 8399)	1
  (0, 1061)	1
  (0, 16044)	3
  (0, 11104)	2
  (0, 11051)	1
  (0, 6759)	1
  (0, 5437)	2
  (0, 8758)	2
  (0, 9474)	3
  (0, 8379)	1
  (0, 3998)	1
  (0, 14430)	1
  (0, 10754)	1


In [20]:
X_names = count_vect.get_feature_names()
print(X_names)

['00', '000', '007', '05', '10', '100', '1000', '101', '102', '103', '105', '106', '107', '108', '10th', '11', '113', '115', '11th', '12', '126', '129', '13', '132', '137', '13th', '14', '15', '15th', '16', '1600', '16x9', '17', '17th', '18', '180', '1800s', '1869', '1871', '18th', '19', '1900', '1914', '1925', '1928', '1933', '1939', '1940s', '1947', '1948', '1949', '1950', '1950s', '1954', '1958', '1960', '1960s', '1961', '1962', '1963', '1964', '1966', '1967', '1968', '1969', '1970', '1970s', '1971', '1972', '1973', '1974', '1976', '1977', '1978', '1979', '1980', '1980s', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1990s', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '19th', '20', '200', '2000', '2001', '2017', '2020', '2029', '20s', '20th', '21', '2176', '22', '23', '24', '25', '25th', '26', '26th', '27', '28', '29', '2d', '30', '300', '3000', '30th', '31', '32', '33', '35', '36', '37', '39', '40', '400', '43', '45', '

In [23]:
print(X_count_vect.toarray())
X_vount_vect = pd.DataFrame(X_count_vect.toarray(),columns = X_names)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
print(X_vount_vect[])

      00  000  007  05  10  100  1000  101  102  103  ...    zones  zoo  \
0      0    0    0   0  10    0     0    0    0    0  ...        0    0   
1      0    0    0   0   0    0     0    0    0    0  ...        0    0   
2      0    0    0   0   0    0     0    0    0    0  ...        0    0   
3      0    0    0   0   0    0     0    0    0    0  ...        0    0   
4      0    0    0   0   0    0     0    0    0    0  ...        0    0   
5      0    0    0   0   1    0     0    0    0    0  ...        0    0   
6      0    0    0   0   0    0     0    0    0    0  ...        0    0   
7      0    0    0   0   0    0     0    0    0    0  ...        0    0   
8      0    0    0   0   0    0     0    0    0    0  ...        0    0   
9      0    0    0   0   7    0     0    0    0    0  ...        0    0   
10     0    0    0   0   0    0     0    0    0    0  ...        0    0   
11     0    0    0   0   0    0     0    0    0    0  ...        0    0   
12     0    0    0   0   

In [25]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [26]:
X_train_cv,X_test_cv,y_train_cv,y_test_cv = train_test_split(X_count_vect,y,test_size=0.25,random_state=5)

In [29]:
print(X_train_cv.shape)
print(X_test_cv.shape)

(1500, 16228)
(500, 16228)


In [38]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model = gnb.fit(X_train_cv.toarray(),y_train_cv)
y_pred_gnb = model.predict(X_test_cv.toarray())
print(y_pred_gnb[0:20])
print(y_test_cv[0:20])

[0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0]
51      0
1327    1
1488    1
1432    1
417     0
269     0
191     0
1889    1
1343    1
1791    1
436     0
156     0
1856    1
1468    1
266     0
660     0
1738    1
492     0
1521    1
33      0
dtype: int64


In [43]:
from sklearn.naive_bayes import MultinomialNB
clf_cv = MultinomialNB()
clf_cv.fit(X_train_cv,y_train_cv)
y_pred_cv = clf_cv.predict(X_test_cv)
print(y_pred_cv[0:20])
print(y_pred_gnb[0:20])
print(y_test_cv[0:20])

[0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0]
[0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0]
51      0
1327    1
1488    1
1432    1
417     0
269     0
191     0
1889    1
1343    1
1791    1
436     0
156     0
1856    1
1468    1
266     0
660     0
1738    1
492     0
1521    1
33      0
dtype: int64


In [45]:
print(metrics.accuracy_score(y_test_cv,y_pred_cv))
print(confusion_matrix(y_test_cv,y_pred_cv))

1.0
[[258   0]
 [  0 242]]
